### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by g-karthik** [ytsvetko/qvec#2]
I'm running QVEC as per the provided instructions and this is the error I get. My input word vectors file follows the word2vec convention (Line 1: [vocab_size] [vector_dimension], all future lines contain [word] [vector]).

```
Traceback (most recent call last):
  File "qvec-python2.7.py", line 208, in <module>
    main()
  File "qvec-python2.7.py", line 189, in main
    vsm_matrix.AddMatrix(args.in_vectors, top_k)
  File "qvec-python2.7.py", line 127, in AddMatrix
    val = float(val)
ValueError: could not convert string to float: cleves
```

Could you please let me know what changes I'll have to make to get this to work? Thanks!

**Comment by sanjanasri** [comment]
getting the same error.. Any help would be appreciated

**Comment by ytsvetko** [comment]
Use python 3.

**Comment by sanjanasri** [comment]
Hi, 
     I used python3,  yet, I get the same error

**Comment by sanjanasri** [comment]
Thank You Sir, its working fine now :)
